
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class Entrada extends javax.swing.JFrame {
    //Fila 3, Asiento 7
    /**
     * Creates new form Entrada
     */
    public Entrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_creacionCarros = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_modelo = new javax.swing.JTextField();
        tf_marca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sp_velocidad = new javax.swing.JSpinner();
        bt_crearCarro = new javax.swing.JButton();
        jd_partida = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcb_juga2 = new javax.swing.JComboBox<>();
        jcb_jugador1 = new javax.swing.JComboBox<>();
        jllable = new javax.swing.JLabel();
        jllable1 = new javax.swing.JLabel();
        jllable2 = new javax.swing.JLabel();
        jllable3 = new javax.swing.JLabel();
        jllable4 = new javax.swing.JLabel();
        jllable5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jl_jug2Marca = new javax.swing.JLabel();
        jl_jug2Modelo = new javax.swing.JLabel();
        jl_jug1Marca = new javax.swing.JLabel();
        jl_jug2Velocidad = new javax.swing.JLabel();
        jl_jug1Modelo = new javax.swing.JLabel();
        jl_jug1Velocidad = new javax.swing.JLabel();
        jd_jugar = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jl_cronometro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jl_nombreCarro2 = new javax.swing.JLabel();
        jl_nombreCarro1 = new javax.swing.JLabel();
        jpb_carro2 = new javax.swing.JProgressBar();
        jpb_carro1 = new javax.swing.JProgressBar();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Creacion de Carros");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 38, 229, 54));

        tf_modelo.setBackground(new java.awt.Color(204, 204, 255));
        tf_modelo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(tf_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 277, -1));

        tf_marca.setBackground(new java.awt.Color(204, 204, 255));
        tf_marca.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(tf_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 155, 277, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Modelo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 50, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Marca");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 40, -1));
        jPanel2.add(sp_velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, -1));

        bt_crearCarro.setText("Crear Carro");
        bt_crearCarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearCarroMouseClicked(evt);
            }
        });
        bt_crearCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearCarroActionPerformed(evt);
            }
        });
        jPanel2.add(bt_crearCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 110, -1));

        javax.swing.GroupLayout jd_creacionCarrosLayout = new javax.swing.GroupLayout(jd_creacionCarros.getContentPane());
        jd_creacionCarros.getContentPane().setLayout(jd_creacionCarrosLayout);
        jd_creacionCarrosLayout.setHorizontalGroup(
            jd_creacionCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );
        jd_creacionCarrosLayout.setVerticalGroup(
            jd_creacionCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Partida");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 40));

        jButton3.setText("Crear Carro");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 120, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Jugador 2 ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 60, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Jugador 1 ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jcb_juga2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_juga2ItemStateChanged(evt);
            }
        });
        jPanel3.add(jcb_juga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 150, -1));

        jcb_jugador1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_jugador1ItemStateChanged(evt);
            }
        });
        jPanel3.add(jcb_jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, -1));

        jllable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jllable.setForeground(new java.awt.Color(0, 0, 0));
        jllable.setText("Marca");
        jPanel3.add(jllable, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 80, 20));

        jllable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jllable1.setForeground(new java.awt.Color(0, 0, 0));
        jllable1.setText("Modelo");
        jPanel3.add(jllable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 80, 20));

        jllable2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jllable2.setForeground(new java.awt.Color(0, 0, 0));
        jllable2.setText("Marca");
        jPanel3.add(jllable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, 20));

        jllable3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jllable3.setForeground(new java.awt.Color(0, 0, 0));
        jllable3.setText("Velocidad");
        jPanel3.add(jllable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 80, 20));

        jllable4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jllable4.setForeground(new java.awt.Color(0, 0, 0));
        jllable4.setText("Modelo");
        jPanel3.add(jllable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 80, 20));

        jllable5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jllable5.setForeground(new java.awt.Color(0, 0, 0));
        jllable5.setText("Velocidad");
        jPanel3.add(jllable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, 20));

        jButton4.setText("Iniciar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 120, 30));

        jl_jug2Marca.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jl_jug2Marca.setForeground(new java.awt.Color(0, 0, 0));
        jl_jug2Marca.setText("pp");
        jPanel3.add(jl_jug2Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 100, -1));

        jl_jug2Modelo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jl_jug2Modelo.setForeground(new java.awt.Color(0, 0, 0));
        jl_jug2Modelo.setText("pp");
        jPanel3.add(jl_jug2Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 100, -1));

        jl_jug1Marca.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jl_jug1Marca.setForeground(new java.awt.Color(0, 0, 0));
        jl_jug1Marca.setText("pp");
        jPanel3.add(jl_jug1Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, -1));

        jl_jug2Velocidad.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jl_jug2Velocidad.setForeground(new java.awt.Color(0, 0, 0));
        jl_jug2Velocidad.setText("pp");
        jPanel3.add(jl_jug2Velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 100, -1));

        jl_jug1Modelo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jl_jug1Modelo.setForeground(new java.awt.Color(0, 0, 0));
        jl_jug1Modelo.setText("pp");
        jPanel3.add(jl_jug1Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, -1));

        jl_jug1Velocidad.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jl_jug1Velocidad.setForeground(new java.awt.Color(0, 0, 0));
        jl_jug1Velocidad.setText("pp");
        jPanel3.add(jl_jug1Velocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, -1));

        javax.swing.GroupLayout jd_partidaLayout = new javax.swing.GroupLayout(jd_partida.getContentPane());
        jd_partida.getContentPane().setLayout(jd_partidaLayout);
        jd_partidaLayout.setHorizontalGroup(
            jd_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        jd_partidaLayout.setVerticalGroup(
            jd_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 51));
        jLabel8.setText("Tiempo");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 40));

        jl_cronometro.setText("cronometro");
        jPanel4.add(jl_cronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 100, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 51));
        jLabel9.setText("Progreso");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 110, -1));

        jl_nombreCarro2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_nombreCarro2.setText("nombre carro 1");
        jPanel4.add(jl_nombreCarro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 160, -1));

        jl_nombreCarro1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_nombreCarro1.setText("nombre carro 1");
        jPanel4.add(jl_nombreCarro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 160, -1));

        jpb_carro2.setMaximum(500);
        jpb_carro2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jpb_carro2StateChanged(evt);
            }
        });
        jPanel4.add(jpb_carro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 240, 40));

        jpb_carro1.setMaximum(500);
        jpb_carro1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jpb_carro1StateChanged(evt);
            }
        });
        jPanel4.add(jpb_carro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 240, 40));

        jButton5.setBackground(new java.awt.Color(255, 255, 51));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Iniciar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        javax.swing.GroupLayout jd_jugarLayout = new javax.swing.GroupLayout(jd_jugar.getContentPane());
        jd_jugar.getContentPane().setLayout(jd_jugarLayout);
        jd_jugarLayout.setHorizontalGroup(
            jd_jugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        jd_jugarLayout.setVerticalGroup(
            jd_jugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Boroa's Racing");

        jButton1.setBackground(new java.awt.Color(255, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Entrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Salir");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addGap(55, 55, 55)
                .addComponent(jButton2)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
//        adminCarros ac = new adminCarros("./carrosPapoy");
//        ac.cargarArchivo();
//        DefaultComboBoxModel modeloJug1 = (DefaultComboBoxModel)jcb_jugador1.getModel();
//        DefaultComboBoxModel modeloJug2 = (DefaultComboBoxModel)jcb_juga2.getModel();
//        modeloJug1.removeAllElements();
//        modeloJug2.removeAllElements();
//        
//        for (int i = 0; i < ac.getListacarros().size(); i++) {
//            Carro carrito = ac.getListacarros().get(i);
//            modeloJug1.addElement(carrito);
//            modeloJug2.addElement(carrito);
//        }
        
        this.setVisible(false);
        //jd_partida.setLocationRelativeTo(null);
        jd_partida.pack();
        jd_partida.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jd_partida.setVisible(false);
        //jd_creacionCarros.setLocationRelativeTo(null);
        jd_creacionCarros.pack();
        jd_creacionCarros.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void bt_crearCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearCarroMouseClicked
        
        String marca = tf_marca.getText();
        String modelo = tf_modelo.getText();
        int vel = (Integer)sp_velocidad.getValue();
        
        Carro car = new Carro(marca, modelo, vel);
        adminCarros ac = new adminCarros("./carrosPapoy");
        DefaultComboBoxModel modeloJug1 = (DefaultComboBoxModel)jcb_jugador1.getModel();
        DefaultComboBoxModel modeloJug2 = (DefaultComboBoxModel)jcb_juga2.getModel();
        ac.cargarArchivo();
        
        ac.getListacarros().add(car);
        ac.escribirArchivo();
        
//        DefaultComboBoxModel modeloJug1 = (DefaultComboBoxModel)jcb_jugador1.getModel();
//        DefaultComboBoxModel modeloJug2 = (DefaultComboBoxModel)jcb_juga2.getModel();
        modeloJug1.removeAllElements();
        modeloJug2.removeAllElements();
        
        for (int i = 0; i < ac.getListacarros().size(); i++) {
            Carro carrito = ac.getListacarros().get(i);
            modeloJug1.addElement(carrito);
            modeloJug2.addElement(carrito);
        }
        
        jd_creacionCarros.setVisible(false);
        jd_partida.pack();
        jd_partida.setLocationRelativeTo(null);
        jd_partida.setVisible(true);
            
        tf_marca.setText("");
        tf_modelo.setText("");
        sp_velocidad.setValue(0);
        
    }//GEN-LAST:event_bt_crearCarroMouseClicked

    private void jcb_jugador1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_jugador1ItemStateChanged
       DefaultComboBoxModel modelo = (DefaultComboBoxModel)jcb_jugador1.getModel();
       Carro carrito = (Carro)modelo.getSelectedItem();
       jl_jug1Marca.setText(carrito.getMarca());
       jl_jug1Modelo.setText(carrito.getModelo());
       jl_jug1Velocidad.setText(String.valueOf(carrito.getVelocidad())); 
        
    
    }//GEN-LAST:event_jcb_jugador1ItemStateChanged

    private void jcb_juga2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_juga2ItemStateChanged
       DefaultComboBoxModel modelo = (DefaultComboBoxModel)jcb_juga2.getModel();
        Carro carrito = (Carro)modelo.getSelectedItem();
        jl_jug2Marca.setText(carrito.getMarca());
        jl_jug2Modelo.setText(carrito.getModelo());
        jl_jug2Velocidad.setText(String.valueOf(carrito.getVelocidad())); 
    }//GEN-LAST:event_jcb_juga2ItemStateChanged

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)jcb_jugador1.getModel();
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel)jcb_juga2.getModel();
        Carro car1 = (Carro)modelo.getSelectedItem();
        Carro car2 = (Carro)modelo2.getSelectedItem();
        jl_nombreCarro1.setText(car1.getModelo());
        jl_nombreCarro2.setText(car2.getModelo());
        jd_partida.setVisible(false);
        jd_jugar.pack();
        jd_jugar.setVisible(true);
        
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel)jcb_jugador1.getModel();
        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel)jcb_juga2.getModel();
        Carro car1 = (Carro)modelo.getSelectedItem();
        Carro car2 = (Carro)modelo2.getSelectedItem();
        
        adminBarras barritas = new adminBarras(jpb_carro1, jpb_carro2, car1.getVelocidad(), car2.getVelocidad(), true);
        barritas.run();
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void bt_crearCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearCarroActionPerformed
        
        
        
    }//GEN-LAST:event_bt_crearCarroActionPerformed

    private void jpb_carro1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jpb_carro1StateChanged
        
        if (jpb_carro1.getValue() == 500) {
            JOptionPane.showMessageDialog(jd_jugar, "El jugador 1 ha ganado");
        }
    }//GEN-LAST:event_jpb_carro1StateChanged

    private void jpb_carro2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jpb_carro2StateChanged
        if (jpb_carro2.getValue() == 500) {
            JOptionPane.showMessageDialog(jd_jugar, "El jugador 2 ha ganado");
        }
    }//GEN-LAST:event_jpb_carro2StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_crearCarro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> jcb_juga2;
    private javax.swing.JComboBox<String> jcb_jugador1;
    private javax.swing.JDialog jd_creacionCarros;
    private javax.swing.JDialog jd_jugar;
    private javax.swing.JDialog jd_partida;
    private javax.swing.JLabel jl_cronometro;
    private javax.swing.JLabel jl_jug1Marca;
    private javax.swing.JLabel jl_jug1Modelo;
    private javax.swing.JLabel jl_jug1Velocidad;
    private javax.swing.JLabel jl_jug2Marca;
    private javax.swing.JLabel jl_jug2Modelo;
    private javax.swing.JLabel jl_jug2Velocidad;
    private javax.swing.JLabel jl_nombreCarro1;
    private javax.swing.JLabel jl_nombreCarro2;
    private javax.swing.JLabel jllable;
    private javax.swing.JLabel jllable1;
    private javax.swing.JLabel jllable2;
    private javax.swing.JLabel jllable3;
    private javax.swing.JLabel jllable4;
    private javax.swing.JLabel jllable5;
    private javax.swing.JProgressBar jpb_carro1;
    private javax.swing.JProgressBar jpb_carro2;
    private javax.swing.JSpinner sp_velocidad;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_modelo;
    // End of variables declaration//GEN-END:variables


}
